export { default as LogoB } from './logo_blue'
export { default as LogoW } from './logo_white'
export { default as LogoCombB } from './logo_combined_blue'
export { default as LogoCombW } from './logo_combined_white'
export { default as LogotypeB } from './logotype_blue'
export { default as LogotypeW } from './logotype_white'
export { default as PhoneB } from './phone_blue'
export { default as PhoneW } from './phone_white'
