backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: settings
    label: Settings
    delete: false
    editor:
      preview: false
    files:
      - name: general
        label: Site settings
        description: General site settings
        file: src/global/settings.json
        fields:
          - label: SEO
            name: seo
            widget: object
            fields:
              - label: Title
                name: title
                widget: string
              - label: Description
                name: descr
                widget: text
          - label: Top Nav phone
            name: topNavTel
            widget: string
          - label: Showcase settings
            name: showcase
            widget: object
            fields:
              - {label: Number of showcase items on frontpage, name: front_limit, widget: number, min: 3, max: 12}
          - label: Footer CTA
            name: footer_cta
            widget: object
            fields:
              - {label: Heading, name: heading, widget: string}
              - {label: Body, name: body, widget: text}
              - {label: CTA, name: cta, widget: string}
          - label: Footer
            name: footer
            widget: object
            fields:
              - label: Columns
                name: columns
                widget: list
                fields:
                  - {label: Body, name: body, widget: text}
  - name: showcases
    label: Showcases
    label_singular: showcase
    description: >
      Description to be added
    folder: src/pages/showcase
    create: true
    editor:
      preview: false
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - label: TemplateKey
        name: templateKey
        required: true
        widget: hidden
        default: showcase
      - label: Title
        name: title
        widget: string
      - label: Image
        name: image
        widget: image
      - label: Image descr
        name: alt
        widget: string
      - label: Tags
        name: tags
        widget: list
        fields:
          - {label: Tag, name: tag, widget: string}
      - label: Category
        name: category
        widget: select
        options: ["Domy pod klucz", "Komercyjne"]
      - label: Section
        name: showcaseSection01
        widget: object
        fields:
          - {label: Heading, name: heading, widget: text}
          - {label: Body, name: body, widget: text}
      - label: Section
        name: showcaseSection02
        widget: object
        fields:
          - {label: Heading, name: heading, widget: text}
          - {label: Body, name: body, widget: text}
          - {label: Image, name: image, widget: image}
          - {label: Image descr, name: alt, widget: string}
      - label: Section
        name: showcaseSection03
        widget: list
        fields:
          - {label: Heading, name: heading, widget: string}
          - {label: Body, name: body, widget: text}
      - label: Section
        name: showcaseSection04
        widget: object
        fields:
          - {label: Heading, name: heading, widget: text}
          - {label: Body, name: body, widget: text}
          - {label: Image, name: image, widget: image}
          - {label: Image descr, name: alt, widget: string}
      - label: Section
        name: showcaseSection05
        widget: object
        fields:
          - {label: Heading, name: heading, widget: string}
          - {label: Body, name: body, widget: text}
          - label: Accordions
            name: accordions
            widget: list
            fields:
              - {label: Heading, name: heading, widget: string}
              - {label: Body, name: body, widget: text}
      - label: Section
        name: showcaseSection06
        widget: list
        fields:
          - {label: Image, name: image, widget: image}
          - {label: Image descr, name: alt, widget: string}
      - label: Section
        name: showcaseSection07
        widget: list
        fields:
          - {label: Value, name: value, widget: string}
          - {label: Addition, name: addition, widget: string}
          - {label: Description, name: description, widget: string}
      - label: Section
        name: showcaseSection08
        widget: object
        fields:
          - {label: Heading, name: heading, widget: string}
          - label: Items
            name: items
            widget: list
            fields:
              - {label: Icon, name: icon, widget: image}
              - {label: Heading, name: heading, widget: string}
              - {label: Description, name: descr, widget: text}
      - label: Section
        name: showcaseSection09
        widget: list
        fields:
          - {label: Image, name: image, widget: image}
          - {label: Image descr, name: alt, widget: string}
  - name: pages
    label: Pages
    editor:
      preview: false
    files:
      - file: src/pages/index.md
        label: Strona głowna
        name: index
        fields:
          - label: templateKey
            name: templateKey
            widget: hidden
            default: index-page
          - label: sortOrder
            name: sortOrder
            widget: hidden
            default: 1
          - label: Title
            name: title
            widget: string
            default: Strona głowna
          - label: Landing screen
            name: landing
            widget: object
            fields:
            - {label: Heading, name: heading, widget: text}
            - label: Box
              name: box01
              widget: object
              fields:
                - {label: Heading, name: heading, widget: text}
                - {label: Body, name: body, widget: text}
                - {label: CTA, name: cta, widget: string}
                - {label: Image, name: image, widget: image}
                - {label: Image descr, name: alt, widget: string}
            - label: Box
              name: box02
              widget: object
              fields:
                - {label: Heading, name: heading, widget: text}
                - {label: Body, name: body, widget: text}
                - {label: CTA, name: cta, widget: string}
                - {label: Image, name: image, widget: image}
                - {label: Image descr, name: alt, widget: string}
          - label: Section
            name: indexSection01
            widget: object
            fields:
              - {label: Heading, name: heading, widget: text}
              - {label: Body, name: body, widget: text}
              - {label: Image, name: image, widget: image}
              - {label: Image descr, name: alt, widget: string}
          - label: Image
            name: image
            widget: image
          - label: Image descr
            name: alt
            widget: string
          - label: Section
            name: indexSection02
            widget: object
            fields:
              - {label: Heading, name: heading, widget: text}
              - {label: Body, name: body, widget: text}
          - label: Section
            name: indexSection03
            widget: list
            fields:
              - {label: Value, name: value, widget: number}
              - {label: Description, name: desc, widget: string}
              - {label: Special character, name: special, widget: string}
          - label: Section
            name: indexSection04
            widget: object
            fields:
              - {label: Heading, name: heading, widget: text}
              - {label: Body, name: body, widget: text}
              - label: Items
                name: items
                widget: list
                fields:
                - {label: Icon, name: icon, widget: image}
                - {label: Heading, name: heading, widget: string}
                - {label: Body, name: body, widget: text}
      - file: src/pages/domy-pod-klucz/index.md
        label: Domy pod klucz
        name: domy-pod-klucz
        fields:
          - label: templateKey
            name: templateKey
            widget: hidden
            default: domy-pod-klucz
          - label: sortOrder
            name: sortOrder
            widget: hidden
            default: 2
          - label: Title
            name: title
            widget: string
            default: Domy pod klucz
          - label: Landing screen
            name: landing
            widget: object
            fields:
              - {label: Heading, name: heading, widget: text}
              - {label: Body, name: body, widget: text}
              - {label: CTA, name: cta, widget: string}
              - {label: Image, name: image, widget: image}
              - {label: Image descr, name: alt, widget: string}
          - label: Section
            name: domySection01
            widget: object
            fields:
              - {label: Heading, name: heading, widget: text}
              - {label: Body, name: body, widget: text}
              - label: Accordions
                name: accordions
                widget: list
                fields:
                  - {label: Heading, name: heading, widget: string}
                  - {label: Body, name: body, widget: markdown}
          - label: Image
            name: image
            widget: image
          - label: Image descr
            name: alt
            widget: string
          - label: Section
            name: domySection02
            widget: object
            fields:
              - {label: Heading, name: heading, widget: text}
              - {label: Body, name: body, widget: text}
          - label: Table
            name: domySection03
            widget: object
            fields:
              - label: Header
                name: header
                widget: object
                fields:
                  - label: Left side
                    name: lhs
                    widget: object
                    fields:
                      - {label: Image, name: image, widget: image, required: true}
                      - {label: Text, name: text, widget: text, required: false}
                      - {label: Small text, name: small, widget: string, required: false}
                  - label: Right side
                    name: rhs
                    widget: object
                    fields:
                      - {label: Image, name: image, widget: image, required: true}
                      - {label: Text, name: text, widget: text, required: false}
                      - {label: Small text, name: small, widget: string, required: false}
              - label: Row
                name: row
                widget: list
                fields:
                  - {label: Heading, name: heading, widget: string, required: false}
                  - label: Left side
                    name: lhs
                    widget: object
                    fields:
                      - label: Item
                        name: item
                        widget: list
                        fields:
                          - {label: Image, name: image, widget: image, required: true}
                          - {label: Big text, name: big, widget: text, required: false}
                          - {label: Text, name: text, widget: text, required: false}
                  - label: Right side
                    name: rhs
                    widget: object
                    fields:
                      - label: Item
                        name: item
                        widget: list
                        fields:
                          - {label: Image, name: image, widget: image, required: true}
                          - {label: Big text, name: big, widget: text, required: false}
                          - {label: Text, name: text, widget: text, required: false}
      - file: src/pages/uslugi-inzynieryjne/index.md
        label: Usługi inżynieryjne
        name: uslugi-inzynieryjne
        fields:
          - label: templateKey
            name: templateKey
            widget: hidden
            default: uslugi-inzynieryjne
          - label: sortOrder
            name: sortOrder
            widget: hidden
            default: 3
          - label: Title
            name: title
            widget: string
            default: Usługi inżynieryjne
          - label: Landing screen
            name: landing
            widget: object
            fields:
              - {label: Heading, name: heading, widget: text}
              - {label: Image, name: image, widget: image}
              - {label: Image descr, name: alt, widget: string}
              - {label: Body, name: body, widget: text}
              - {label: CTA, name: cta, widget: string}
          - label: Section
            name: uslugiSection01
            widget: object
            fields:
              - {label: Heading, name: heading, widget: text}
              - label: Accordions
                name: accordions
                widget: list
                fields:
                - {label: Heading, name: heading, widget: string}
                - {label: Body, name: body, widget: markdown}
          - label: Section
            name: uslugiSection02
            widget: object
            fields:
              - {label: Heading, name: heading, widget: text}
              - label: Carousel
                name: carousel
                widget: list
                fields:
                  - {label: Body, name: body, widget: text}
                  - {label: Name, name: name, widget: string}
                  - {label: Link, name: link, required: false, widget: string}
                  - {label: Link text, name: linkText, widget: string}
      - file: src/pages/realizacje/index.md
        label: Realizacje
        name: realizacje
        fields:
          - label: templateKey
            name: templateKey
            widget: hidden
            default: realizacje
          - label: sortOrder
            name: sortOrder
            widget: hidden
            default: 4
          - label: Title
            name: title
            widget: string
            default: Realizacje
      - file: src/pages/o-nas/index.md
        label: O nas
        name: o-nas
        fields:
          - label: templateKey
            name: templateKey
            widget: hidden
            default: o-nas
          - label: sortOrder
            name: sortOrder
            widget: hidden
            default: 5
          - label: Title
            name: title
            widget: string
            default: O nas
          - label: Section
            name: oSection01
            widget: object
            fields:
              - {label: Heading, name: heading, widget: text}
              - {label: Body, name: body, widget: text}
              - {label: Image, name: image, widget: image}
              - {label: Image descr, name: alt, widget: string}
          - label: Section
            name: oSection02
            widget: object
            fields:
              - {label: Heading, name: heading, widget: text}
              - {label: Body, name: body, widget: text}
              - {label: Image, name: image, widget: image}
              - {label: Image descr, name: alt, widget: string}
          - label: Section
            name: oSection03
            widget: object
            fields:
              - {label: Heading, name: heading, widget: text}
              - label: Cards
                name: cards
                widget: list
                fields:
                  - {label: Image, name: image, widget: image}
                  - {label: Image descr, name: alt, widget: string}
                  - {label: Name, name: name, widget: string}
                  - {label: Description, name: descr, widget: text}
      - file: src/pages/kontakt/index.md
        label: Kontakt
        name: kontakt
        fields:
          - label: templateKey
            name: templateKey
            widget: hidden
            default: kontakt
          - label: sortOrder
            name: sortOrder
            widget: hidden
            default: 6
          - label: Title
            name: title
            widget: string
            default: Kontakt
          - label: Section
            name: kontaktSection01
            widget: object
            fields:
              - {label: Heading, name: heading, widget: text}
              - {label: Body, name: body, widget: markdown}
              - {label: Image, name: image, widget: image}
              - {label: Image descr, name: alt, widget: string}
              - {label: Helmet, name: helmet, widget: image}
          - label: Section
            name: kontaktSection02
            widget: object
            fields:
              - {label: Heading, name: heading, widget: text}
              - {label: Body, name: body, widget: text}
              - label: Options
                name: options
                widget: list
                fields:
                  - {label: Option, name: option, widget: string}
