backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: settings
    label: Settings
    delete: false
    editor:
      preview: false
    files:
      - name: general
        label: Site settings
        description: General site settings
        file: src/global/settings.json
        fields:
          - label: Global title
            name: 'site_title'
            widget: string
            default: Eskon
          - label: Showcase settings
            name: showcase
            widget: object
            fields:
              - {label: Number of showcase items on frontpage, name: front_limit, widget: number, min: 3, max: 12}
          - label: Footer CTA
            name: footer_cta
            widget: object
            fields:
              - {label: Heading, name: heading, widget: string}
              - {label: Body, name: body, widget: text}
              - {label: CTA, name: cta, widget: string}
          - label: Footer
            name: footer
            widget: object
            fields:
              - label: Columns
                name: columns
                widget: list
                fields:
                  - {label: Body, name: body, widget: text}
  - name: showcases
    label: Showcases
    label_singular: showcase
    description: >
      Description to be added
    folder: src/pages/showcase
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - label: TemplateKey
        name: templateKey
        required: true
        widget: hidden
        default: showcase
      - label: Title
        name: title
        widget: string
      - label: Image
        name: image
        required: false
        widget: image
      - label: Space
        name: space
        widget: number
      - label: Category
        name: category
        widget: string
      - label: Started
        name: dateFrom
        widget: date
        format: MMM Do YY
      - label: Finished
        name: dateTo
        required: false
        widget: date
        format: MMM Do YY
      - label: Section
        name: section01
        widget: object
        fields:
          - {label: Heading, name: heading, widget: markdown}
          - label: Column
            name: col01
            widget: object
            fields:
              - {label: Body, name: body}
          - label: Column
            name: col02
            widget: object
            required: false
            fields:
              - {label: Body, name: body}
      - label: Section
        name: section02
        widget: object
        fields:
          - {label: Heading, name: heading, widget: string}
          - {label: Body, name: body, widget: markdown}
          - {label: Image, name: image, required: false, widget: image}
      - label: Section
        name: section03
        widget: list
        fields:
          - {label: Heading, name: heading, widget: string}
          - {label: Body, name: body, widget: text}
      - label: Section
        name: section04
        widget: object
        fields:
          - {label: Heading, name: heading, widget: string}
          - {label: Body, name: body, widget: text}
          - {label: Image, name: image, required: false, widget: image}
      - label: Section
        name: sectio05
        widget: object
        fields:
          - {label: Heading, name: heading, widget: string}
          - {label: Body, name: body, widget: text}
          - label: Accordions
            name: accordions
            widget: list
            fields:
              - {label: Heading, name: heading, widget: string}
              - {label: Body, name: body, widget: text}
              - {label: Open, name: isOpen, widget: boolean}
      - label: Section
        name: section06
        widget: list
        fields:
          - {label: Image, name: image, required: false, widget: image}
      - label: Section
        name: section07
        widget: list
        fields:
          - {label: Value, name: value, widget: string}
          - {label: Description, name: description, widget: string}
      - label: Section
        name: section 08
        widget: object
        fields:
          - {label: Heading, name: heading, widget: string}
          - label: Items
            name: items
            widget: list
            fields:
              - {label: Icon, name: icon, widget: string}
              - {label: Heading, name: heading, widget: string}
              - {label: Description, name: descr, widget: text}
      - label: Section
        name: section09
        widget: list
        fields:
          - {label: Image, name: image, required: false, widget: image}
  - name: pages
    label: Pages
    files:
      - file: src/pages/index.md
        label: Strona głowna
        name: index
        fields:
          - label: templateKey
            name: templateKey
            widget: hidden
            default: index-page
          - label: Title
            name: title
            widget: string
            default: Strona głowna
          - label: Landing screen
            name: landing
            widget: object
            fields:
            - {label: Heading, name: heading, widget: string}
            - label: Box
              name: box01
              widget: object
              fields:
                - {label: Heading, name: heading, widget: string}
                - {label: Body, name: body, widget: text}
                - {label: CTA, name: cta, widget: string}
                - {label: Image, name: image, required: false, widget: image}
            - label: Box
              name: box02
              widget: object
              fields:
                - {label: Heading, name: heading, widget: string}
                - {label: Body, name: body, widget: text}
                - {label: CTA, name: cta, widget: string}
                - {label: Image, name: image, required: false, widget: image}
          - label: Section
            name: section01
            widget: object
            fields:
              - {label: Heading, name: heading, widget: string}
              - {label: Body, name: body, widget: text}
              - {label: Image, name: image, required: false, widget: image}
          - label: Section
            name: section02
            widget: object
            fields:
              - {label: Heading, name: heading, widget: string}
              -  {label: Body, name: body, widget: text}
          - label: Counters
            name: counters
            widget: list
            fields:
              - {label: Value, name: value, widget: number}
              - {label: Description, name: desc, widget: string}
          - label: Section
            name: section03
            widget: object
            fields:
              - {label: Heading, name: heading, widget: string}
              - {label: Body, name: body, widget: text}
              - label: Items
                name: items
                widget: list
                fields:
                - {label: Icon, name: icon, required: false, widget: string}
                - {label: Heading, name: heading, widget: string}
                - {label: Body, name: body, widget: text}
      - file: src/pages/domy-pod-klucz/index.md
        label: Domy pod klucz
        name: domy-pod-klucz
        fields:
          - label: templateKey
            name: templateKey
            widget: hidden
            default: domy-pod-klucz
          - label: Title
            name: title
            widget: string
            default: Domy pod klucz
          - label: Landing screen
            name: landing
            widget: object
            fields:
              - {label: Heading, name: heading, widget: string}
              - {label: Body, name: body, widget: text}
              - {label: CTA, name: cta, widget: string}
          - label: Section
            name: section01
            widget: object
            fields:
              - {label: Heading, name: heading, widget: string}
              - {label: Body, name: body, widget: text}
              - label: Accordions
                name: accordions
                widget: list
                fields:
                  - {label: Heading, name: heading, widget: string}
                  - {label: Body, name: body, widget: markdown}
                  - {label: Open, name: isOpen, widget: boolean}
          - label: Section
            name: section02
            widget: object
            fields:
              - {label: Image, name: image, required: false, widget: image}
              - {label: Heading, name: heading, widget: string}
              - {label: Body, name: body, widget: text}
          - label: Table
            name: table
            widget: object
            fields: []
      - file: src/pages/uslugi-inzynieryjne/index.md
        label: Usługi inżynieryjne
        name: uslugi-inzynieryjne
        fields:
          - label: templateKey
            name: templateKey
            widget: hidden
            default: uslugi-inzynieryjne
          - label: Title
            name: title
            widget: string
            default: Usługi inżynieryjne
          - label: Landing screen
            name: landing
            widget: object
            fields:
              - {label: Heading, name: heading, widget: string}
              - {label: Image, required: false, name: image, widget: image}
              - {label: Body, name: body, widget: text}
              - {label: CTA, name: cta, widget: string}
          - label: Section
            name: section01
            widget: object
            fields:
              - {label: Heading, name: heading, widget: string}
              - label: Accordions
                name: accordions
                widget: list
                fields:
                - {label: Heading, name: heading, widget: string}
                - {label: Body, name: body, widget: markdown}
                - {label: Open, name: isOpen, widget: boolean}
          - label: Section
            name: section02
            widget: object
            fields:
              - {label: Heading, name: heading, widget: string}
              - label: Carousel
                name: carousel
                widget: list
                fields:
                  - {label: Body, name: body, widget: string}
                  - {label: Name, name: name, widget: string}
                  - {label: Link, name: link, widget: string}
                  - {label: Link text, name: linkText, widget: string}
      - file: src/pages/realizacje/index.md
        label: Realizacje
        name: realizacje
        fields:
          - label: templateKey
            name: templateKey
            widget: hidden
            default: realizacje
          - label: Title
            name: title
            widget: string
            default: Realizacje
      - file: src/pages/o-nas/index.md
        label: O nas
        name: o-nas
        fields:
          - label: templateKey
            name: templateKey
            widget: hidden
            default: o-nas
          - label: Title
            name: title
            widget: string
            default: O nas
          - label: Section
            name: section01
            widget: object
            fields:
              - {label: Heading, name: heading, widget: string}
              - {label: Body, name: body, widget: text}
              - {label: Image, name: image, required: false, widget: image}
          - label: Section
            name: section02
            widget: object
            fields:
              - {label: Heading, name: heading, widget: string}
              - {label: Body, name: body, widget: string}
              - {label: Image, name: image, required: false, widget: image}
          - label: Section
            name: section03
            widget: object
            fields:
              - {label: Heading, name: heading, widget: string}
              - label: Cards
                name: cards
                widget: list
                fields:
                  - {label: Image, name: image, required: false, widget: image}
                  - {label: Name, name: name, widget: string}
                  - {label: Description, name: descr, widget: markdown}
      - file: src/pages/kontakt/index.md
        label: Kontakt
        name: kontakt
        fields:
          - label: templateKey
            name: templateKey
            widget: hidden
            default: kontakt
          - label: Title
            name: title
            widget: string
            default: Kontakt
          - label: Section
            name: section01
            widget: object
            fields:
              - {label: Heading, name: heading, widget: string}
              - {label: Body, name: body, widget: markdown}
              - {label: Image, name: image, required: false, widget: image}
          - label: Section
            name: section02
            widget: object
            fields:
              - {label: Heading, name: heading, widget: string}
              - {label: Body, name: body, widget: string}
              - label: Options
                name: options
                widget: list
                field:
                  - {label: Option, name: option, widget: string}
